version: '3.8'

services:
  # PostgreSQL база данных для основного приложения
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: wallet_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: wallet_db, wallet_db_test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-multiple-databases.sh:/docker-entrypoint-initdb.d/init-multiple-databases.sh  # Скрипт для создания нескольких БД
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Наше FastAPI приложение
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/wallet_db
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  tests:
    build: .
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/wallet_db_test
      DATABASE_TEST_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/wallet_db_test
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "pytest -v --tb=short"
    profiles: ["test"]

volumes:
  postgres_data: